// Mock Database Sandbox for RecipeDB2 Frontend & Playground
// Expanded with multi-cultural recipes and computational gastronomy statistics

export const mockRecipesInfo = {
  success: "true",
  message: "Recipes fetched successfully (Sandbox Mode).",
  payload: {
    data: [
      {
        _id: "6405721fa13d0d2d35890d69",
        Recipe_id: "2610",
        Calories: "196.0",
        cook_time: "30",
        prep_time: "15",
        servings: "4",
        Recipe_title: "Egyptian Lentil Soup",
        total_time: "45",
        Region: "Middle Eastern",
        Sub_region: "Egyptian",
        Continent: "African",
        Source: "AllRecipes",
        "Carbohydrate, by difference (g)": "146.7606",
        "Energy (kcal)": "805.6975",
        "Protein (g)": "49.554",
        "Total lipid (fat) (g)": "5.6564",
        Processes: "place||heat||cook||remove||cool||blend||smooth||stir||heat",
        Utensils: "pot",
        vegan: "0.0",
        pescetarian: "0.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "0.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "Heat olive oil in a large pot over medium heat. Sauté chopped onions, garlic, and carrots until softened. Add rinsed red lentils, cumin, coriander, and broth. Bring to a boil, simmer for 30 minutes. Blend until smooth, season with salt and pepper, and stir. Serve warm with lemon wedges."
      },
      {
        _id: "6405721fa13d0d2d35890d6a",
        Recipe_id: "2611",
        Calories: "80.0",
        cook_time: "35",
        prep_time: "10",
        servings: "4",
        Recipe_title: "Egyptian Green Beans with Carrots",
        total_time: "45",
        Region: "Middle Eastern",
        Sub_region: "Egyptian",
        Continent: "African",
        Source: "AllRecipes",
        "Carbohydrate, by difference (g)": "39.3312",
        "Energy (kcal)": "386.767",
        "Protein (g)": "15.5638",
        "Total lipid (fat) (g)": "19.7239",
        Utensils: "pot",
        Processes: "heat||heat||cook||stir||stir||cook||stirring||pour||stir||boil||add||boil||simmer",
        vegan: "1.0",
        pescetarian: "1.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "0.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "Heat olive oil in a pot. Sauté finely chopped onions and garlic until translucent. Add diced carrots and fresh cut green beans; cook for 5 minutes. Pour in tomatoes and paste. Bring to a boil, add stock, and simmer for 35 minutes."
      },
      {
        _id: "6405721fa13d0d2d35890e01",
        Recipe_id: "3501",
        Calories: "310.0",
        cook_time: "20",
        prep_time: "15",
        servings: "4",
        Recipe_title: "Tandoori Paneer Tikka",
        total_time: "35",
        Region: "Indian",
        Sub_region: "North Indian",
        Continent: "Asian",
        Source: "IndianHealthyRecipes",
        "Carbohydrate, by difference (g)": "22.5000",
        "Energy (kcal)": "620.4000",
        "Protein (g)": "38.6000",
        "Total lipid (fat) (g)": "48.2000",
        Utensils: "skewer||grill||bowl",
        Processes: "whisk||mix||marinate||skewer||grill||baste||roast",
        vegan: "0.0",
        pescetarian: "0.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "1.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "Whisk Greek yogurt with ginger-garlic paste, tandoori masala, red chili powder, kasuri methi, and lemon juice. Fold in paneer cubes, diced bell peppers, and red onions. Marinate for 30 minutes. Thread onto skewers and grill at 400°F (200°C) for 15-20 minutes, basting with melted butter once, until roasted and charred on edges."
      },
      {
        _id: "6405721fa13d0d2d35890e02",
        Recipe_id: "3502",
        Calories: "420.0",
        cook_time: "15",
        prep_time: "15",
        servings: "2",
        Recipe_title: "Tuscan Sun-Dried Tomato Pasta",
        total_time: "30",
        Region: "Western European",
        Sub_region: "Italian",
        Continent: "European",
        Source: "GialloZafferano",
        "Carbohydrate, by difference (g)": "112.4000",
        "Energy (kcal)": "840.6000",
        "Protein (g)": "24.5000",
        "Total lipid (fat) (g)": "32.1000",
        Utensils: "pot||skillet||tong",
        Processes: "boil||drain||sauté||simmer||toss||garnish",
        vegan: "0.0",
        pescetarian: "0.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "1.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "Boil penne pasta in salted water until al dente. In a skillet, sauté garlic, sun-dried tomatoes, and red pepper flakes in olive oil. Stir in fresh baby spinach and heavy cream; simmer for 5 minutes until sauce thickens. Toss drained pasta into the skillet, stirring to coat. Garnish with grated Parmesan cheese and toasted pine nuts."
      },
      {
        _id: "6405721fa13d0d2d35890e03",
        Recipe_id: "3503",
        Calories: "380.0",
        cook_time: "25",
        prep_time: "20",
        servings: "2",
        Recipe_title: "Shoyu Miso Ramen",
        total_time: "45",
        Region: "East Asian",
        Sub_region: "Japanese",
        Continent: "Asian",
        Source: "JustOneCookbook",
        "Carbohydrate, by difference (g)": "78.2000",
        "Energy (kcal)": "760.3000",
        "Protein (g)": "29.4000",
        "Total lipid (fat) (g)": "14.8000",
        Utensils: "saucepan||bowl||chopstick",
        Processes: "boil||whisk||simmer||assemble||garnish",
        vegan: "0.0",
        pescetarian: "1.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "0.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "Boil ramen noodles according to package instructions and drain. In a saucepan, combine dashi stock, mirin, soy sauce, and white miso paste, whisking until smooth; simmer gently. Pour hot broth into serving bowls, add noodles, and assemble ramen with soft-boiled egg halves, nori seaweed sheets, sliced green onions, and bamboo shoots."
      },
      {
        _id: "6405721fa13d0d2d35890d6b",
        Recipe_id: "2612",
        Calories: "339.0",
        cook_time: "120",
        prep_time: "15",
        servings: "4",
        Recipe_title: "Egyptian Bamia",
        total_time: "135",
        Region: "Middle Eastern",
        Sub_region: "Egyptian",
        Continent: "African",
        Source: "AllRecipes",
        "Carbohydrate, by difference (g)": "34.0004",
        "Energy (kcal)": "1762.7662",
        "Protein (g)": "82.9034",
        "Total lipid (fat) (g)": "146.8971",
        Utensils: "saucepan||oven||dish||oven",
        Processes: "heat||heat||cook||stir||mix||cook||stir||stir||season||boil||simmer||stir||preheat||stir||boil||cover||bake",
        vegan: "0.0",
        pescetarian: "0.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "0.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "In a saucepan, brown meat cubes, sauté onions and garlic. Add tomato sauce, broth, okra (bamia), coriander, and lemon juice. Simmer for 30 minutes. Transfer to an oven dish, bake at 375°F (190°C) for 90 minutes."
      },
      {
        _id: "6405721fa13d0d2d35890d6c",
        Recipe_id: "2613",
        Calories: "409.0",
        cook_time: "15",
        prep_time: "15",
        servings: "3",
        Recipe_title: "Magpie's Easy Falafel Cakes",
        total_time: "60",
        Region: "Middle Eastern",
        Sub_region: "Egyptian",
        Continent: "African",
        Source: "AllRecipes",
        "Carbohydrate, by difference (g)": "225.1172",
        "Energy (kcal)": "1686.8298",
        "Protein (g)": "67.8589",
        "Total lipid (fat) (g)": "62.4829",
        Utensils: "skillet||processor||bowl||cup||dish||tablespoon||skillet",
        Processes: "cook||smooth||transfer||stir||cover||chill||place||roll||heat||heat||cook",
        vegan: "0.0",
        pescetarian: "0.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "1.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "Process chickpeas, garlic, onion, and spices until smooth but coarsely textured. Stir in breadcrumbs and yogurt. Chill for 30 minutes, roll into patties, and shallow fry in hot oil until golden brown."
      },
      {
        _id: "6405721fa13d0d2d35890d6d",
        Recipe_id: "2614",
        Calories: "45.0",
        cook_time: "5",
        prep_time: "20",
        servings: "24",
        Recipe_title: "Dukkah",
        total_time: "25",
        Region: "Middle Eastern",
        Sub_region: "Egyptian",
        Continent: "African",
        Source: "AllRecipes",
        "Carbohydrate, by difference (g)": "83.0609",
        "Energy (kcal)": "1006.238",
        "Protein (g)": "26.18",
        "Total lipid (fat) (g)": "73.1713",
        Utensils: "oven||sheet||skillet||bowl||skillet||pan||processor||bowl||processor||bowl",
        Processes: "preheat||place||pour||fold||cover||remove||cool||heat||stirring||pop||transfer||process||pour||place||process||stir||season||mix",
        vegan: "1.0",
        pescetarian: "1.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "0.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "Roast hazelnuts in oven at 350°F. Rub off skins. Toast sesame seeds, coriander, and cumin in a dry skillet. Pulse everything briefly in a processor until coarsely ground, then stir in salt and pepper."
      },
      {
        _id: "6405721fa13d0d2d35890d6e",
        Recipe_id: "2615",
        Calories: "934.0",
        cook_time: "30",
        prep_time: "30",
        servings: "8",
        Recipe_title: "Om Ali",
        total_time: "60",
        Region: "Middle Eastern",
        Sub_region: "Egyptian",
        Continent: "African",
        Source: "AllRecipes",
        "Carbohydrate, by difference (g)": "543.3028",
        "Energy (kcal)": "4117.4667",
        "Protein (g)": "46.5988",
        "Total lipid (fat) (g)": "212.1542",
        Utensils: "oven||dish||oven||oven||oven||bowl||dish||saucepan||dish||oven",
        Processes: "preheat||place||place||remove||preheat||break||stir||spread||boil||heat||beat||cream||spread||place||serve",
        vegan: "0.0",
        pescetarian: "0.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "0.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "Bake puff pastry until golden. Tear into pieces and toss with nuts, raisins, and coconut in a baking dish. Boil milk, sugar, and vanilla, and pour over. Spread whipped heavy cream on top and bake for 15 mins."
      },
      {
        _id: "6405721fa13d0d2d35890d6f",
        Recipe_id: "2616",
        Calories: "299.0",
        cook_time: "25",
        prep_time: "10",
        servings: "4",
        Recipe_title: "Egyptian Rice Pudding (Kishk)",
        total_time: "35",
        Region: "Middle Eastern",
        Sub_region: "Egyptian",
        Continent: "African",
        Source: "AllRecipes",
        "Carbohydrate, by difference (g)": "81.2955",
        "Energy (kcal)": "1043.9806",
        "Protein (g)": "68.5817",
        "Total lipid (fat) (g)": "52.6077",
        Utensils: "saucepan||skillet||bowl",
        Processes: "heat||heat||add||simmer||heat||heat||cook||stirring||mix||whisk||smooth||blend||smooth||boil||reduce||heat||simmer||garnish",
        vegan: "0.0",
        pescetarian: "0.0",
        ovo_vegetarian: "0.0",
        lacto_vegetarian: "0.0",
        ovo_lacto_vegetarian: "0.0",
        instructions: "Boil rice until soft. Add milk, sugar, and cardamom; simmer. Stir in cornstarch mixture and cook until thickened. Pour into bowls, cool, and garnish with caramelized onions and roasted nuts."
      }
    ],
    pagination: {
      totalCount: 118083,
      totalPages: 11809,
      currentPage: 1,
      itemsPerPage: 10
    }
  }
};

export const mockRecipeOfDay = {
  success: "true",
  message: "Recipe fetched successfully (Sandbox Mode).",
  payload: {
    data: {
      _id: "6405732fa13d0d2d358ac639",
      Recipe_id: "143953",
      Calories: "274.8",
      cook_time: "0",
      prep_time: "0",
      servings: "36 crackers",
      Recipe_title: "Cheese Krispies Crackers",
      total_time: "50",
      url: "http://www.geniuskitchen.com/recipe/cheese-krispies-crackers-74463",
      Region: "Canadian",
      Sub_region: "Canadian",
      Continent: "North American",
      Source: "Geniuskitchen",
      img_url: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?q=80&w=600&auto=format&fit=crop",
      "Carbohydrate, by difference (g)": "108.9547",
      "Energy (kcal)": "1579.4352",
      "Protein (g)": "46.4264",
      "Total lipid (fat) (g)": "116.0104",
      Utensils: "processor||bowl||cutter",
      Processes: "blend||add||add||remove||mix||place||roll||place",
      vegan: "0.0",
      pescetarian: "0.0",
      ovo_vegetarian: "0.0",
      lacto_vegetarian: "1.0",
      ovo_lacto_vegetarian: "0.0",
      instructions: "In a processor, blend sharp Cheddar cheese and butter. Add cayenne pepper, salt, and flour; pulse until crumbly. Mix in Rice Krispies manually, roll out thin, cut into squares, and bake at 350°F for 12-15 minutes."
    }
  }
};

export const mockRecipeWithExclusions = {
  success: true,
  message: "Recipe fetched successfully (cached sandbox).",
  payload: {
    Recipe_title: "Habanero, Mango, Pineapple Salsa",
    Calories: "44.3",
    total_time: "25",
    servings: "2 quarts",
    Sub_region: "Rest Caribbean",
    Region: "Caribbean",
    ingredients: [
      { name: "habanero pepper" },
      { name: "pineapple" },
      { name: "mango" },
      { name: "cucumber" },
      { name: "cilantro leaf" }
    ],
    instructions: "Peel and dice mangoes and pineapple. Seed and dice cucumber and tomatoes. Finely chop red onion, yellow bell pepper, and habaneros. Combine in a large bowl, cover and refrigerate for 2-3 hours. Serve with chips."
  }
};

export const mockNutritionInfo = {
  success: "true",
  message: "Nutrition information fetched successfully (Sandbox Mode).",
  payload: {
    data: [
      {
        recipeTitle: "Egyptian Lentil Soup",
        _id: "64c4197fc6779f7b31e6dd71",
        Recipe_id: "2610",
        ndb_id: "2013",
        "Ash (g)": "0.0271",
        "Calcium, Ca (mg)": "3.1905",
        "Carbohydrate, by difference (g)": "0.2475",
        "Cholesterol (mg)": "0.0",
        "Copper, Cu (mg)": "0.0044",
        "Energy (kJ)": "5.6025",
        "Energy (kcal)": "1.341",
        "Fatty acids, total monounsaturated (g)": "0.0611",
        "Fatty acids, total polyunsaturated (g)": "0.0079",
        "Fatty acids, total saturated (g)": "0.0045",
        "Fiber, total dietary (g)": "0.1886",
        "Iron, Fe (mg)": "0.0734",
        "Magnesium, Mg (mg)": "1.485",
        "Potassium, K (mg)": "5.7015",
        "Protein (g)": "0.0557",
        "Sodium, Na (mg)": "0.1575",
        "Total lipid (fat) (g)": "0.08",
        "Vitamin C, total ascorbic acid (mg)": "0.0945",
        "Water (g)": "0.0399",
        "Zinc, Zn (mg)": "0.0212"
      }
    ]
  }
};

// Computational Gastronomy Pre-computed Research Data
export const mockAnalyticsData = {
  averageCaloriesByContinent: [
    { continent: "African", calories: 690 },
    { continent: "Asian", calories: 580 },
    { continent: "European", calories: 840 },
    { continent: "North American", calories: 920 },
    { continent: "Caribbean", calories: 480 }
  ],
  macronutrientDistribution: [
    { name: "Carbs", percentage: 48, color: "var(--accent-orange)" },
    { name: "Protein", percentage: 22, color: "var(--accent-purple)" },
    { name: "Fats", percentage: 30, color: "var(--accent-emerald)" }
  ],
  dietaryPrevalence: [
    { category: "Lacto-Veg", count: 24500 },
    { category: "Vegan", count: 8120 },
    { category: "Pescetarian", count: 12050 },
    { category: "Non-Veg", count: 73413 }
  ]
};
